- name: Install Docker dependencies
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: Set up Docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Install Docker
  yum:
    name: docker-ce
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

