- name: Create Groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
  loop:
    - { name: 'bmgroup', gid: '1100' }
    - { name: 'batchgroup', gid: '1108' }
    - { name: 'dockerappgroup', gid: '10000' }
  become: yes

- name: Create Users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    shell: "{{ item.shell }}"
    password: "{{ item.password | default(omit) }}"
    createhome: yes
  with_items:
    - { name: 'bmadmin', uid: '1100', group: 'bmgroup', shell: '/bin/bash', password: "{{ 'tEsts3cr3t!' | password_hash('sha512') }}" }
    - { name: 'batch', uid: '1108', group: 'batchgroup', shell: '/bin/bash' }
    - { name: 'dockerapp', uid: '10000', group: 'dockerappgroup', shell: '/bin/bash' }
  become: yes

- name: Grant sudo access to bmadmin
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^bmadmin'
    line: 'bmadmin ALL=(ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: yes

