- name: Install Docker
  yum:
    name: docker-ce
    state: present
  become: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

